eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/
server:
  port: 8081
spring:
  application:
    name: index
management:
  security:
    #关闭安全验证，否则访问refresh端点时会提示权限不足
    enabled: false